### ISSUE TITLE
Tree representation and dataset questions in general

### ISSUE THREAD

**Issue by andre-cavalheiro** [thunlp/NLP-THU#3]
Hello,

# Question 1, regarding tree structures:
 
For HW2 we get a few datasets with a tree-like representations of our sentences.

I can see that the sentiment value of smaller parts of our sentence can be meaningful in determining the sentiment of the entire sentence but i cannot understand how can we use that information while training our model. Furthermore, importing such a structure by hand seems to be complex and it would be pretty nice if you could recommend an existing function in some package that would do it for us. 

# Question 2, regarding the data sets.

In the README of stanfordSentimentTreebank, there are both sentence_ids and phrase_ids. 

From what i read , the train, test and dev sets were created from the sentences in datasetSentences.txt, but the sentiment labels are associated with the phrases from dictionary.txt . How are we supposed to know which sentiments are associated to which sentences then? Is there a way of doing it without the importing the tree-like structure?

**Comment by EdwardZH** [comment]
For problem 1, I think tree structure and other architectures can help you. In general, each smaller part will indicate semantic tendency. If you add these supervised signal, it will help the model to learn more semantic patterns through the entire sentence.

**Comment by EdwardZH** [comment]
For problem 2, the original data is a little confused, and I think the processed data (illustrated in the assignment) will help you.
